# Generated by Django 5.2.15 on 2026-06-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('destination_country', models.CharField(max_length=120)),
                ('destination_city', models.CharField(blank=True, max_length=120)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_email', models.EmailField(max_length=254)),
                ('buyer_phone', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('matched', 'Matched'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='categories.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
